apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test-goose-agent-26051801
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-goose-agent-26051801
  name: test-goose-agent-26051801
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: test-goose-agent-26051801
  type: ClusterIP
